// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using comercioLocalAPI;

#nullable disable

namespace comercioLocalAPI.Migrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20230325232718_newMigration2")]
    partial class newMigration2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("comercioLocalAPI.Model.Cliente", b =>
                {
                    b.Property<Guid>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("cnpj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cpf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("endereço")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nomeEmpresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nomeResponsavel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClienteId");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("comercioLocalAPI.Model.Fornecedor", b =>
                {
                    b.Property<Guid>("FornecedorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("cnpj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("contadorVendas")
                        .HasColumnType("int");

                    b.Property<string>("cpf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("endereço")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nomeEmpresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nomeResponsavel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FornecedorId");

                    b.ToTable("Fornecedor");
                });

            modelBuilder.Entity("comercioLocalAPI.Model.Negociacao", b =>
                {
                    b.Property<Guid>("NegociacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<Guid?>("ClienteId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FornecedorId")
                        .HasColumnType("int");

                    b.Property<Guid?>("FornecedorId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("data")
                        .HasColumnType("datetime2");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("NegociacaoId");

                    b.HasIndex("ClienteId1");

                    b.HasIndex("FornecedorId1");

                    b.ToTable("Negociacoe");
                });

            modelBuilder.Entity("comercioLocalAPI.Model.Produto", b =>
                {
                    b.Property<Guid>("ProdutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FornecedorId")
                        .HasColumnType("int");

                    b.Property<Guid?>("FornecedorId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NegociacaoId")
                        .HasColumnType("int");

                    b.Property<Guid?>("NegociacaoId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("descricaoProduto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nomeProduto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("quantidadeProduto")
                        .HasColumnType("int");

                    b.Property<double>("valorProuto")
                        .HasColumnType("float");

                    b.HasKey("ProdutoId");

                    b.HasIndex("FornecedorId1");

                    b.HasIndex("NegociacaoId1");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("comercioLocalAPI.Model.Negociacao", b =>
                {
                    b.HasOne("comercioLocalAPI.Model.Cliente", null)
                        .WithMany("negociacoes")
                        .HasForeignKey("ClienteId1");

                    b.HasOne("comercioLocalAPI.Model.Fornecedor", null)
                        .WithMany("negociacoes")
                        .HasForeignKey("FornecedorId1");
                });

            modelBuilder.Entity("comercioLocalAPI.Model.Produto", b =>
                {
                    b.HasOne("comercioLocalAPI.Model.Fornecedor", null)
                        .WithMany("produtos")
                        .HasForeignKey("FornecedorId1");

                    b.HasOne("comercioLocalAPI.Model.Negociacao", null)
                        .WithMany("produtos")
                        .HasForeignKey("NegociacaoId1");
                });

            modelBuilder.Entity("comercioLocalAPI.Model.Cliente", b =>
                {
                    b.Navigation("negociacoes");
                });

            modelBuilder.Entity("comercioLocalAPI.Model.Fornecedor", b =>
                {
                    b.Navigation("negociacoes");

                    b.Navigation("produtos");
                });

            modelBuilder.Entity("comercioLocalAPI.Model.Negociacao", b =>
                {
                    b.Navigation("produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
